plugins {
    id 'java'
    id 'application'
    id 'jacoco'
    id "org.sonarqube" version "5.0.0.4638"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 8
    options.encoding = 'UTF-8'
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test

    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    implementation 'org.apache.logging.log4j:log4j-api:2.25.4'
    implementation 'org.apache.logging.log4j:log4j-core:2.25.4'
}

jacoco {
    toolVersion = "0.8.11"
}

sonar {
    properties {
        property "sonar.projectKey", "henriqueotogami_road-to-java-oca"
        property "sonar.organization", "henriqueotogami"
        property "sonar.host.url", "https://sonarcloud.io"

        property "sonar.sources", "src/main/java"
        property "sonar.tests", "src/test/java"
        property "sonar.junit.reportPaths", "build/test-results/test"
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"
    }
}

application {
    // Define the main class for the application.
    mainClass = 'org.example.App'
}

check {
    dependsOn 'chapter01', 'chapter02', 'chapter03', 'chapter04', 'chapter05', 'chapter06'
}


tasks.register('hello') {
    doLast {
        println("Hello, Gradle!")
    }
}

tasks.register('chapter01', Test) {
    description = "Run Chapter 01 tests"
    group = "oca-chapters"

    useJUnitPlatform()

    filter {
        includeTestsMatching "oca.chapter01.*"
    }
}

tasks.register('chapter02', Test) {
    description = "Run Chapter 02 tests"
    group = "oca-chapters"

    useJUnitPlatform()

    filter {
        includeTestsMatching "oca.chapter02.*"
    }
}

tasks.register('chapter03', Test) {
    description = "Run Chapter 03 tests"
    group = "oca-chapters"

    useJUnitPlatform()

    filter {
        includeTestsMatching "oca.chapter03.*"
    }
}

tasks.register('chapter04', Test) {
    description = "Run Chapter 04 tests"
    group = "oca-chapters"

    useJUnitPlatform()

    filter {
        includeTestsMatching "oca.chapter04.*"
    }
}

tasks.register('chapter05', Test) {
    description = "Run Chapter 05 tests"
    group = "oca-chapters"

    useJUnitPlatform()

    filter {
        includeTestsMatching "oca.chapter05.*"
    }
}

tasks.register('chapter06', Test) {
    description = "Run Chapter 06 tests"
    group = "oca-chapters"

    useJUnitPlatform()

    filter {
        includeTestsMatching "oca.chapter06.*"
    }
}