plugins {
    id 'java'
    id 'application'
    id "org.sonarqube" version "3.5.0.2730"
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

task hello {
    doLast {
        println("Hello, Gradle!")
    }
}

sonarqube {
    properties {
        property "sonar.projectKey", "henriqueotogami_road-to-java-oca"
        property "sonar.organization", "henriqueotogami"
        property "sonar.host.url", "https://sonarcloud.io"
    }
}